---
- hosts: localhost 
  vars_files:
    - ../vault.yml
  tasks:
    - name: Add Helm repo for Cert-Manager
      shell: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
      ignore_errors: yes
      
    - name: Install Cert-Manager
      ansible.builtin.command:
        cmd: |
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.14.5 --set installCRDs=true
          
      ignore_errors: yes
      
    - name: Create secret for Azure DNS Service Principal
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: azure-dns-credentials
          namespace: cert-manager
        type: Opaque
        data:
          client-id: "{{ CLIENT_ID | b64encode }}"
          client-secret: "{{ CLIENT_SECRET | b64encode }}"
          subscription-id: "{{ SUBSCRIPTION_ID | b64encode }}"
          tenant-id: "{{ TENANT_ID | b64encode }}"
        EOF

    - name: Configure Azure DNS Issuer
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-azure
          namespace: cert-manager
        spec:
          acme:
            server: https://acme-v02.api.letsencrypt.org/directory
            email: "{{ technical_email }}"
            preferredChain: ISRG Root X1
            privateKeySecretRef:
              name: letsencrypt-azure-key
            solvers:
            - dns01:
                azureDNS:
                  clientID: "{{ CLIENT_ID }}"
                  clientSecretSecretRef:
                    name: azure-dns-credentials 
                    key: client-secret
                  subscriptionID: "{{ SUBSCRIPTION_ID }}"
                  tenantID: "{{ TENANT_ID }}"
                  resourceGroupName: "{{ global_dns_resource_group_name }}"
                  hostedZoneName: "{{ dns_private_zone_name }}"
                  environment: AzurePublicCloud
              selector:
                dnsZones:
                - "{{ dns_private_zone_name }}"
        EOF

