---
- hosts: masters
  become: yes
  vars_files:
    - ../../../../vault.yml
  tasks:
    - name: Add Helm repo for Cert-Manager
      shell: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
      ignore_errors: yes

    - name: Install Cert-Manager
      ansible.builtin.command:
        cmd: |
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.13.2 --set installCRDs=true
      ignore_errors: yes

    - name: Create AWS Route53 secret
      shell : |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: route53-secret
          namespace: cert-manager
        type: Opaque
        data:
          accessKey: "{{ aws_DNS_access_key_id | b64encode}}"
          secretKey: "{{ aws_DNS_password | b64encode }}"
        EOF

    - name: Create AWS Route53 ClusterIssuer
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-route53
        spec:
          acme:
            email: "{{ technical_email }}"
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: letsencrypt-route53-key
            solvers:
            - dns01:
                route53:
                  region: "{{ aws_region }}"
                  hostedZoneID: "{{ aws_DNS_zone_id }}"
                  accessKeyID: "{{ aws_DNS_access_key_id }}"
                  secretAccessKeySecretRef:
                    name: route53-secret
                    key: secretKey
        EOF
