apiVersion: v1
items:
- apiVersion: v1
  data:
    root-cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIIC/TCCAeWgAwIBAgIRANoPwmpWO3be3ZXd1cIZR6wwDQYJKoZIhvcNAQELBQAw
      GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMzExMTYxODAxNTJaFw0zMzEx
      MTMxODAxNTJaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
      DQEBAQUAA4IBDwAwggEKAoIBAQC6oqNGtMvbtTmtQFQlQx+eHJ2k1DRLnFtMk/fu
      nDM0GMJRExUpCH+FE5xRhJmiAbRehhv7Iw6opRAcmgy0sIpUwduW61sPdgrzI2Yg
      JfcfrhPFYIq05sNa5n2rHXqBsBKhjEyb3hHT/V9L9+cBk+nWk7iWQV6ASY+S4LYr
      PZzAjrqN9lfFMplNx6yoXo99BvBonx+ByNGz5ZSutzQQRQoJor/LULJOn5ZGYZ+i
      oWfWTAHYCes7Ku5i7b7MxbRlKldUEkfSGZhElqAT+chrkIIR45HwoAJPgcmMzXZf
      Z01k6MDYUihlgkg1HUMgSLLZM72bHbsXjv19YI9fgsHmxbUDAgMBAAGjQjBAMA4G
      A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQxpV8OwbCU
      vJ/Gj/b4ha6AniridTANBgkqhkiG9w0BAQsFAAOCAQEApPZ5rEUTmtW2pBBEYKci
      zybCuKYFa+qagjqf1EGdzOIpD5i6MjF1Y1nvv8DVq1pGYuZofJFRZ7rzVVAYF/J0
      +ko7Q69/lsrBqoTQqmpiB2T4S27MV7yMvNf5F3PSP6d8ir3x3Am+srQGlueS4H0K
      TBsf4G1X1ZKLc49aWQhh0iNwTUNqZeqnOLVnEDE/GHZrscEt6YRBbhDLHJBiy3Pe
      GYVGp1XDXLVRTrWW1StQF6QSdJFQp1SCWQfAxBtkkLmsoGhKLrS81ao7r9uHy9RT
      tHxa9iMySnAufKqNTo2VpUVUVbKMX1owpbd+17OzfS9vHGBXSNifZXUQ1lM7p21p
      CQ==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2024-03-07T16:28:14Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-root-cert
    namespace: gitlab
    resourceVersion: "50173605"
    uid: 7160c843-c8c8-472b-bd74-8df15b8e0567
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIAUeRhUus3v4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yMzExMTYxNzI1MThaFw0zMzExMTMxNzMwMThaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCs1F2/pGdmOSBlSgunyVMhp/Opxo3jPwugWEZfTJdiAUsQHhD2UbhXRcA0
      63ZKeXZKp0Zw2p9eomfXopJdgeGwV4IfdgkH1w+RHWCEMZwIX4igjz47GTT29oQO
      UmCXAaW9FHAeVfQ+0D5c0ajWpNc/F/kLBW9e17Qb1dSu/elp9DynpiWkv8IhPL8a
      77JsVXjCczYSXDGwf5zyjvENWynZWxYypAwMUsNRcVdesEqxXniChK6EeVvG8ryp
      3YhOZJv4l9h1ogUKpopS4e1o7YW80V0pt9A1rmvyiVn/V/PZIs+Kv1pVOi8RLeg0
      bC+UQh0jK1HZz83De+puAILot5sHAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQP5KSVQOYOPMiKVuszRSVVhqtsgTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAXRh7ym+34
      E2ktFzscB7CLqLO/NDK0R5UFZvQ4PYJ7krLnDFbdq5tvoychOFPG8XxQrvHlzQo7
      N7l9kyv1WylWTTKz5VFzaQmvpcI47sw5JOv2NkKLVsN2vF1Fdibw/B1cwBarkwfY
      Wk8ykf1iDKJclfpNE7TUg0JqEU9glblSh+7r7E8wBVV3ajXXmEPBMMkSXH6lU1Nr
      o0TBc6zM9IdNj6qUH3c9N3BLqA4IqTyaQ1yXpPv4YCXFO81F7Jrh8fB12jij8D+E
      lv8PFEIFHo0NeOEO9vYP0g39Zno9ptvG4/3QLdqQJTyiw6bNY7a/OEQme3uH3W4G
      pJW5PesvKCj0
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-03-07T16:28:14Z"
    name: kube-root-ca.crt
    namespace: gitlab
    resourceVersion: "50173606"
    uid: 78ba424b-78da-4240-87a9-4cc43b36ff0e
kind: List
metadata:
  resourceVersion: ""
