kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: REPLACE-NS-ROLE-user-full-access
  namespace: REPLACE-NAMESPACE
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create"]
