apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: REPLACE-NS-ROLE-user-access
  namespace: REPLACE-NAMESPACE
subjects:
- kind: Group
  name: REPLACE-ID
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: REPLACE-NS-ROLE-user-full-access
  apiGroup: rbac.authorization.k8s.io