apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: d-cicd
  labels:
    jenkins-agent-type: 'jenkins-agent-default'
spec:
  serviceAccountName: 'jenkins-admin'
  tolerations:
    - effect: "NoSchedule"
      key: "apps"
      operator: "Equal"
      value: "cicdagents"
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      command:
        - cat
      tty: true
    - name: ubuntu
      image: ubuntu:latest
      command:
        - sleep
      args:
        - "infinity"
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "500m"
    - name: maven
      image: maven:latest
      command: ["cat"]
      tty: true 
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "500m" 
