apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: d-cicd
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
