---
- name: Set-up AKS Cluster
  hosts: localhost
  tasks:
    - name: Ensure directory exists and is empty
      ansible.builtin.file:
        path: "{{ playbook_dir }}/terraform_outputs"
        state: directory
        mode: '0755'
      register: dir

    - name: Remove all files from directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{ playbook_dir }}/terraform_outputs/*"
      when: dir.changed # noqa: no-handler

    - name: Ensure 'terraform' directory is copied to 'terraform_outputs'
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/terraform/"
        dest: "{{ playbook_dir }}/terraform_outputs/"
        delete: true
        recursive: true

    - name: Prepare Microsoft Entra ID group creation
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/plays/set_group.yml"

    - name: Init terraform
      ansible.builtin.command: terraform init -upgrade
      changed_when: false
      args:
        chdir: "{{ playbook_dir }}/terraform_outputs"

    - name: Terraform plan and apply
      block:
        - name: Terraform plan
          ansible.builtin.command: |
            terraform plan -var-file=envVars.tfvars --out tfplan
          register: result_plan
          changed_when: false
          args:
            chdir: "{{ playbook_dir }}/terraform_outputs"

        - name: Terraform apply
          ansible.builtin.command: |
            terraform apply tfplan
          register: result_apply
          changed_when: false
          args:
            chdir: "{{ playbook_dir }}/terraform_outputs"
      rescue:
        - name: Retry block
          ansible.builtin.command: |
            terraform plan -var-file=envVars.tfvars --out tfplan
            terraform apply tfplan
          register: result_plan
          changed_when: false
          args:
            chdir: "{{ playbook_dir }}/terraform_outputs"
          until: result_plan is succeeded and result_apply is succeeded
          retries: 3
          delay: 5
